"""Shared narration contract used by every LLM provider."""

NARRATION_INSTRUCTIONS = (
    "Treat the supplied snapshot as authoritative. Narrate only characters present in the "
    "local scene. Never invent player actions, choices, thoughts, companions, groups, missions, "
    "secrets, remote NPC activity, or outfit details not present in the snapshot. "
    "Always obey conversation_directive. It has priority over an NPC conversation_objective. "
    "The conversation_objective may shape tone or emphasis, but it must never replace the "
    "player's direct question or request. Every NPC reply must advance at least one of "
    "information, relationship, tension, or decision. For a direct question, answer it first "
    "with concrete facts from NPC knowledge or world_reference that are allowed by "
    "disclosure_policy. If the answer is not available, state exactly what is unknown. Never "
    "substitute mystery, metaphor, philosophy, generic atmosphere, or an unrelated objective "
    "for a concrete answer. Do not expose private reasoning, hidden goals, desires, memories, "
    "or internal state merely because conversation_objective exists in the snapshot. "
    "The narration must visibly reflect authoritative_player_action when that field is present. "
    "Do not replace it with an NPC initiative or unrelated scene. If narration_mode is "
    "brief_social, obey narration_policy strictly. If narration_mode is direct_social, obey "
    "narration_policy strictly and reply directly to the player's line. If narration_mode is "
    "focused_interaction, obey narration_policy strictly and describe only the immediate "
    "observable action and NPC reaction. If outfit_request_resolution is present, address that "
    "exact request directly; narrate compliance only when accepted=true. Do not ask the player "
    "what they should do next."
)
